sudo: required
dist: trusty
language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls

env:
  matrix:
    - NODE_VERSION="8" NPM_VERSION="5" DISPLAY=:99
    - NODE_VERSION="8" NPM_VERSION="6" DISPLAY=:99
    - NODE_VERSION="9" NPM_VERSION="5" DISPLAY=:99
    - NODE_VERSION="10" NPM_VERSION="6" DISPLAY=:99

services:
  - docker

addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g jshint
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit
  - "sh -e /etc/init.d/xvfb start"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - ./docker-build-images.sh
  - cd core
  - npm i
  - npm install .
  - npm run coverage
  - cd ..
  - cd cli
  - npm i
  - npm install . -g
  - npm run test
  - ./runTests.sh
  - cd ..
  - ./docker-build-images.sh
after_script:
  - cd core
  - ../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT  || true
before_install:
  # Prepare node and npm
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION
  - npm install -g snyk
  # Show environment info
  - node --version
  - npm --version
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3499197be7208e15199
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
