# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - NODE_VERSION: "14"
    - NODE_VERSION: "16"
    - NODE_VERSION: "18"

platform:
  - x86
  - x64

cache:
  - AllReadyApp\Web-App\AllReady\node_modules   # node modules for the app
  - '%APPDATA%\npm-cache'                       # npm cache

install:
  - ps: Install-Product node $env:NODE_VERSION
  - node --version
  - npm --version
  - npm install -g jshint
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit

build: off

test_script:
  - cd core
  - npm install .
  - npm test
  - npm install . -g --force
  - cd ..
  - cd cli
  - npm install .
  - npm test
  - npm install . -g --force
  - .\runTests
